### ISSUE TITLE
"Module not found" when using example code

### ISSUE THREAD

**Issue by Nixoncole** [dewald-els/omedacity-js#2]
Hello 👋  fairly new to the open source world (and admittedly NodeJS) and just start to play with your JS package... I'm trying to run the following, which I found in your documentation:
```
import { OmedaCityClient } from "omedacity-js";

(async () => {
  const client = new OmedaCityClient();
  const players = await client.players.get();
})();
```

But I'm getting:
```
node:internal/modules/esm/resolve:264
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/nixoncole/code/omedaJS/node_modules/omedacity-js/dist/collections/builds' imported from /Users/nixoncole/code/omedaJS/node_modules/omedacity-js/dist/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/nixoncole/code/omedaJS/node_modules/omedacity-js/dist/collections/builds'
}
```
My package.json:
```
{
    "name": "testing-omeda",
    "version": "0.0.1",
    "author": "nixoncole",
    "dependencies": {
        "omedacity-js": "^0.6.2"
    },
    "type": "module"
}
```
node version: `Node.js v20.11.0`
npm version: `10.2.4`

I may be attempting to access your code incorrectly, but most of the SO posts I've seen around `ERR_MODULE_NOT_FOUND` seem to be about referencing local files, so I'm not sure what I'm doing wrong :/ 

Thanks!

**Comment by Nixoncole** [comment]
hmmm... It appears I was able to resolve this locally by editing my local copy of files in `node_modules`'s import statements to reference `.js` extensions instead of attempting to implicitly reference from the path. 

e.g. change in `/node_modules/omedacity-js/dist/collections/builds.js`:

**from**
```
import { buildsFindAll, buildsFindById } from "../api/builds";
import { client } from "../api";
```
**to**
```
import { buildsFindAll, buildsFindById } from "../api/builds.js";
import { client } from "../api/index.js";
```

This seems like maybe I'm using a wrong version or something that enforces this style change? Ill try again on a fresh install with node 16 later... 😬

**Comment by dewald-els** [comment]
@Nixoncole  Thanks! I'll take a look. I can switch my local node version to 20 and give it a go! Did you use a JavaScript file?

**Comment by dewald-els** [comment]
@Nixoncole I've just released a new version, should fix the import issue :) It takes a couple of minutes to propagate to npm. The new version is 0.6.3. If you have tested it out, you can close the issue 👍

**Comment by Nixoncole** [comment]
Amazing! Tested with a fresh install of `0.6.3` Thank you 🙏
